### ISSUE TITLE
Sudden Crash at random.

### ISSUE THREAD

**Issue by LunaThePotato** [zly2006/come-back-my-villagers#1]
Hello!

I just wanted to drop in as I've come across this error twice so far and It occurs seemingly at random whenever I'm wandering around the world. I can't seem to understand what seems to be the issue except seeing this mod being mentioned in the error logs shown below:
Hopefully the info helps, thank you for your time! c:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-04-01 02:58:40
Description: Saving entity NBT

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.class_1646.redirect$znc000$come-back-my-villagers$fillRecipesModify(class_1646.java:1151)
	at net.minecraft.class_1646.method_7237(class_1646.java:899)
	at net.minecraft.class_3988.method_8264(class_3988.java:115)
	at net.minecraft.class_3988.method_5652(class_3988.java:172)
	at net.minecraft.class_1646.method_5652(class_1646.java:513)
	at net.minecraft.class_1297.method_5647(class_1297.java:1835)
	at net.minecraft.class_1297.method_5786(class_1297.java:1771)
	at net.minecraft.class_1297.method_5662(class_1297.java:1779)
	at net.minecraft.class_5565.method_31734(class_5565.java:108)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5565.method_31760(class_5565.java:106)
	at net.minecraft.class_5579.method_31812(class_5579.java:299)
	at net.minecraft.class_5579.method_31846(class_5579.java:380)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:762)
	at it.unimi.dsi.fastutil.longs.LongIterable.forEach(LongIterable.java:146)
	at it.unimi.dsi.fastutil.longs.AbstractLongCollection.forEach(AbstractLongCollection.java:153)
	at net.minecraft.class_5579.method_31829(class_5579.java:374)
	at net.minecraft.class_3218.method_14176(class_3218.java:816)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:542)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:566)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1646.redirect$znc000$come-back-my-villagers$fillRecipesModify(class_1646.java:1151)
	at net.minecraft.class_1646.method_7237(class_1646.java:899)
	at net.minecraft.class_3988.method_8264(class_3988.java:115)
	at net.minecraft.class_3988.method_5652(class_3988.java:172)
	at net.minecraft.class_1646.method_5652(class_1646.java:513)

-- Entity being saved --
Details:
	Entity Type: minecraft:villager (net.minecraft.class_1646)
	Entity ID: 6688
	Entity Name: Botanist
	Entity's Exact location: -376.50, 65.00, 3048.29
	Entity's Block location: World: (-377,65,3048), Section: (at 7,1,8 in -24,4,190; chunk contains blocks -384,-64,3040 to -369,319,3055), Region: (-1,5; contains chunks -32,160 to -1,191, blocks -512,-64,2560 to -1,319,3071)
	Entity's Momentum: 0.00, -0.08, 0.02
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_5647(class_1297.java:1835)
	at net.minecraft.class_1297.method_5786(class_1297.java:1771)
	at net.minecraft.class_1297.method_5662(class_1297.java:1779)
	at net.minecraft.class_5565.method_31734(class_5565.java:108)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.class_5565.method_31760(class_5565.java:106)
	at net.minecraft.class_5579.method_31812(class_5579.java:299)
	at net.minecraft.class_5579.method_31846(class_5579.java:380)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:762)
	at it.unimi.dsi.fastutil.longs.LongIterable.forEach(LongIterable.java:146)
	at it.unimi.dsi.fastutil.longs.AbstractLongCollection.forEach(AbstractLongCollection.java:153)
	at net.minecraft.class_5579.method_31829(class_5579.java:374)
	at net.minecraft.class_3218.method_14176(class_3218.java:816)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:542)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:566)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zly2006** [comment]
added a null check, a new release is on the way. please test if this version still crashes:

https://legacy.curseforge.com/minecraft/mc-mods/come-back-my-villagers/files/5226646

**Comment by LunaThePotato** [comment]
Thanks for the fix chief!
I'm not getting any errors so far, (XX **Just ignore..** [_however I believe i have found the source of the error too. I forgot that i had a mod that added a new profession for the villager called the "Botanist" from the Beautify Mod by Suel_ki._] XX) I'd imagine it cause some conflicts to this mod as before when i was trying to trade with it, it would give a disapproval grunt and not trade at all unlike the vanilla villagers. _So i suppose this ends up fixing compatibility for other modded Villager Professions(?)._

But either way , thanks for the quick fix! I'll keep a look out for any other issues if any decides to pop up. c:

**EDIT: O wait its already in the error log ive posted im dumb >,>**

**Comment by zly2006** [comment]
the compatibility issue that other mods may add villager professions has been fixed above XD.
Thanks for your report. it is also my bad not to consider the compatibility.
